language: python
python:
  - 3.5
install:
  - pip install -r requirements/requirements.txt && pip install -r requirements/dev_requirements.txt && pip install .
script:
  - python setup.py test
after_success:
  - codecov