# Generated by Django 2.1.3 on 2018-12-17 19:42

from django.db import migrations, models
import lms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='fb_link',
            field=models.CharField(blank=True, default='', max_length=64, validators=[lms.validators.fb_link_validation]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='insta_link',
            field=models.CharField(blank=True, default='', max_length=64, validators=[lms.validators.insta_link_validation]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='linkedin_link',
            field=models.CharField(blank=True, default='', max_length=64, validators=[lms.validators.linkedin_link_validation]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='vk_link',
            field=models.CharField(blank=True, default='', max_length=64, validators=[lms.validators.vk_link_validation]),
        ),
        migrations.AlterField(
            model_name='student',
            name='fb_link',
            field=models.CharField(blank=True, default='', max_length=64, validators=[lms.validators.fb_link_validation]),
        ),
        migrations.AlterField(
            model_name='student',
            name='insta_link',
            field=models.CharField(blank=True, default='', max_length=64, validators=[lms.validators.insta_link_validation]),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin_link',
            field=models.CharField(blank=True, default='', max_length=64, validators=[lms.validators.linkedin_link_validation]),
        ),
        migrations.AlterField(
            model_name='student',
            name='vk_link',
            field=models.CharField(blank=True, default='', max_length=64, validators=[lms.validators.vk_link_validation]),
        ),
    ]
