# Generated by Django 2.1.3 on 2018-12-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20181217_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='city',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
