# Generated by Django 2.1.4 on 2018-12-13 19:53

from django.db import migrations, models
import lms.objects.validation


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[lms.objects.validation.phone_number_validation]),
        ),
    ]
